### ISSUE TITLE
Falten comentaris al principi del fitxer getC12

### ISSUE THREAD

**Issue by mfarssaccifo** [mfarssaccifo/projecteFinal#46]
Veure comentaris en la documentació. Ha de contenir una descripció, les variables que fa servir com a paràmetres (de fer-ne servir) i el nom de l'autor.

Gràcies.

**Comment by javisastrecifo** [comment]
Sí, el que està pujat al Git és l'únic commit que vaig fer. El tinc preparat. Quan m'hi posi pujo el complet. Gràcies per recordar-ho de totes formes.
